# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # All Vagrant configuration is done here. The most common configuration
    # options are documented and commented below. For a complete reference,
    # please see the online documentation at vagrantup.com.

    # Every Vagrant virtual environment requires a box to build off of.
    config.vm.box = "ubuntu/trusty64"

    config.vm.synced_folder ".", "/vagrant", disabled: true
#    config.vm.synced_folder "./projects", "/projects", nfs: true

    config.vm.provider :virtualbox do |vb|
        vb.memory = 512
        vb.cpus = 1
    end

    ip = "172.17.8.101"
    config.vm.network :private_network, ip: ip

    web_port = 8080
    config.vm.network :forwarded_port, guest: web_port, :host => web_port

    #  config.vm.provision "shell", path: "setup.sh"
    #config.vm.provision "shell", inline: "apt-get update -y"
    #config.vm.provision "shell", inline: "apt-get install -y nodejs-legacy npm git git-core nano"
    #config.vm.provision "shell", inline: "npm install -g express-generator grunt grunt-cli 6to5"
    #config.vm.provision "shell", inline: "git clone https://github.com/JediMindtrick/ExpressAngular-Starter.git /projects/ExpressAngular-Starter"

end
